module Skeles1mod where

-- Haskell module generated by the BNF converter

import Abses1mod
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transE :: E -> Result
transE x = case x of
  Radice e  -> failure x
  Nodo e1 e2  -> failure x
  Nodi e1 e2  -> failure x
  Label n  -> failure x



